### ISSUE TITLE
Field rename raises an error

### ISSUE THREAD

**Issue by lelit** [nicolaiarocci/cerberus#153]
This is what happens trying the example in the documentation:
```
>>> from cerberus import __version__
>>> print(__version__)
0.9.2
>>> from cerberus import Validator
>>> v = Validator({'foo': {'rename': 'bar'}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lele/wip/arstecnica/raccoon/env/local/lib/python2.7/site-packages/cerberus/cerberus.py", line 175, in __init__
    self.validate_schema(self.schema)
  File "/home/lele/wip/arstecnica/raccoon/env/local/lib/python2.7/site-packages/cerberus/cerberus.py", line 451, in validate_schema
    constraint, field))
cerberus.cerberus.SchemaError: unknown rule 'rename' for field 'rename'
```

Am I missing something?

**Comment by funkyfuture** [comment]
that feature is new in version 0.10
