### ISSUE TITLE
Function-based Custom Validation and schema load form JSON/YAML

### ISSUE THREAD

**Issue by hudecof** [nicolaiarocci/cerberus#203]
Hi,

is tehre any way howto load the schema definition form file and using the custom validation function?

The example is in the docs http://docs.python-cerberus.org/en/stable/customize.html#function-validator
There is no way how to pass function reference into JSON/YAML schema reprezentation, so the Error is throwed

json file/representaion
`{"oddity": {"validator": "validate_oddity"}}`

The expected Exception:
```
Traceback (most recent call last):
  File "./cerberus_test01.py", line 74, in <module>
    test_schema_03()
  File "./cerberus_test01.py", line 66, in test_schema_03
    v.validate(document)
  File "/Users/hudecof/devel/sk-nic/sydora/proto/env/lib/python3.5/site-packages/cerberus/cerberus.py", line 236, in validate
    return self._validate(document, schema, update=update, context=context)
  File "/Users/hudecof/devel/sk-nic/sydora/proto/env/lib/python3.5/site-packages/cerberus/cerberus.py", line 282, in _validate
    self._validate_definition(definition, field, value)
  File "/Users/hudecof/devel/sk-nic/sydora/proto/env/lib/python3.5/site-packages/cerberus/cerberus.py", line 349, in _validate_definition
    validator(definition[rule], field, value)
  File "/Users/hudecof/devel/sk-nic/sydora/proto/env/lib/python3.5/site-packages/cerberus/cerberus.py", line 706, in _validate_validator
    validator(field, value, self._error)
TypeError: 'str' object is not callable
```

**Comment by funkyfuture** [comment]
you can use the current code from the master-branch with a [custom validator as method](http://docs.python-cerberus.org/en/latest/customize.html#custom-validators). as this feature is new, any feedback concerning the usage and the documentation is appreciated.
