### ISSUE TITLE
Validation of list item with coerce failed with "'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by andreymal** [nicolaiarocci/cerberus#211]
```python
>>> import cerberus
>>> v = cerberus.Validator({'data': {'type': 'list', 'schema': {'type': 'integer', 'coerce': int}}})
>>> v.validated({'data': ['1', '2']})
{'data': [1, 2]}
>>> v.validated({'data': ['q']})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Cerberus-0.10-py3.4.egg/cerberus/cerberus.py", line 800, in validated
  File "Cerberus-0.10-py3.4.egg/cerberus/cerberus.py", line 776, in validate
  File "Cerberus-0.10-py3.4.egg/cerberus/cerberus.py", line 536, in __normalize_mapping
  File "Cerberus-0.10-py3.4.egg/cerberus/cerberus.py", line 593, in __normalize_containers
    self.__normalize_sequence(field, mapping, schema)
  File "Cerberus-0.10-py3.4.egg/cerberus/cerberus.py", line 645, in __normalize_sequence
    for i in result:
TypeError: 'NoneType' object is not iterable

# But:
>>> v = cerberus.Validator({'data': {'type': 'list', 'schema': {'type': 'integer'}}})
>>> v.validated({'data': ['q']})  # => None
```

**Comment by funkyfuture** [comment]
i wrote a fix for that, also including an option to return the docuemnt when an error occurred.

but i found something else beside that i still want to have a closer look at. within the next days.
